### ISSUE TITLE
picotiny shows only testscreen

### ISSUE THREAD

**Issue by jux1e** [sipeed/TangNano-9K-example#11]
After flashing firmware there is only testscreen displayed via HDMI, UART also isn't working.

Any ideas?

**Comment by jianghy222** [comment]
确实，而且自己综合的比特流 连flash都烧写不进去

**Comment by jianghy222** [comment]
解决了，把编译优化等级改为 -O0 -g 即可 ，-O3等级编译出的文件貌似比-O0要大一倍，而且运行不了。

**Comment by richardklingler** [comment]
Most probably you had to remove in the picotiny constraint file the references to external SPI flash, otherwise it wouldn't synthesize....

But then there is no riscv code, so only test screen is displayed and also console isn't working.

The picotiny.fs file at the projects top directory contains also the riscv code...you could flash this one....

**Comment by wonderfullook** [comment]
Because you did not succeed flashing the bin file into the softcore
